greeting:
  message: Say greeting default
farewell:
  message: Say farewell Goodbye
data:
  username: ${DB_USERNAME:username}
  password: ${DB_PASSWORD:password}
spring:
  redis:
    client-name: dqss
    host: localhost
    port: 6379
    password: test #密码（默认为空）
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
    timeout: 10000ms    #连接超时时间（毫秒）