mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.demo.account.infra.valueobject
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
