apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sample
  labels:
    name: k8s-sample
spec:
  selector:
    matchLabels:
      app: k8s-sample
  template:
    metadata:
      labels:
        app: k8s-sample
    spec:
      containers:
        - name: k8s-sample
          image: k8s-sample:v1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 18088
          volumeMounts:
            - name: k8s-conf   # 与上面的volumes.name保持一致
              mountPath: /user/local/application.yml
              readOnly: true
      volumes:
        - name: k8s-conf
          configMap:
            name: k8s-sample # 指定要使用的configmap名称