#spring:
#  application:
#    name: myGrpcServer
server:
  port: 8081
grpc:
  server:
    port: 9091
spring:
  application:
    name: myGrpcServer
#  cloud:
#    nacos:
#      discovery:
#        server-addr: ${NACOS:127.0.0.1}:8848
#      #        username: nacos
#      #        password: nacos
#      config:
#        import-check.enabled: false
#        file-extension: yaml
#        server-addr: ${NACOS:127.0.0.1}:8848
nacos:
  discovery:
    autoRegister: true
    register:
      ip: 127.0.0.1
      port: 9091
#      weight: 0.6D
#      healthy: false
#      enabled: true
#      ephemeral: true
#      clusterName: GrpcServerCluster
#      groupName: DEFAULT_GROUP
    server-addr: localhost:8848
#    username: nacos
#    password: nacos
    enabled: true
  config:
    server-addr: 127.0.0.1:8848
  application:
    name: myGrpcServer