server:
  port: 8081
  servlet:
    context-path: /adminclient
spring:
  application:
    name: admin-client
  # Spring Boot Admin 监控服务器端地址
  boot:
    admin:
      client:
        url: http://localhost:9001

management:
  endpoints:
    web:
      exposure:
        include: "*"
  ## 增加 spring boot admin 日志 方式一
  endpoint:
    logfile:
      ## spring boot admin 日志 需要和 logback 配置路径一致
      external-file: 'logs/admin-client-today.log'

## 增加 spring boot admin 日志 方式二
#logging:
  ## spring boot admin 日志 需要和logback 配置路径一致
#  file:
#    name: 'logs/admin-client-today.log'
#  pattern:
#    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'