apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-sample-config
data:
  application.yml: |-
    greeting:
      message: Say Hello to the World from k8s
    farewell:
      message: Say farewell from k8s
    myconfig:
      message: This is my config message